config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  resources :recursos
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recursos, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, :message, :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/recurso.rb
class Recurso < ApplicationRecord
  belongs_to :category
  has_one_attached :image

  validates :titulo, presence: true
  validates :category_id, presence: true
  validates :url, presence: true
  validates :steam_area, presence: true, inclusion: { in: %w[ Ciencia Tecnología Ingeniería Arte Matemáticas ] }
  validates :resource_type, inclusion: { in: %w[ Artículo Vídeo PDF Libro Curso Herramienta ] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def admin?
    self.admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || locale_from_header || I18n.default_locale
  end

  def locale_from_header
    request.env.fetch("HTTP_ACCEPT_LANGUAGE", "").scan(/[a-z]{2}/).first
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.create(contact_params)

    if @contact.valid? && @contact.save
      ContactMailer.contact_email(@contact).deliver_now
      flash[:notice] = "Tu mensaje ha sido enviado. ¡Gracias!"
      redirect_to root_path
    else
      flash[:alert] = "Por favor, revisa los errores en el formulario."
      redirect_to root_path
    end
  end

  private

  def contact_params
    params.permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recursos_controller.rb
class RecursosController < ApplicationController
  # before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @steam_areas = %w[ Ciencia Tecnología Ingeniería Arte Matemáticas ]

    if params[:category_id].present? &&
      @resources = Recurso.where(category_id: params[category_id])
    else
      @resources = Recurso.all
    end

    if params[:query].present?
      sql_subquery = "titulo LIKE :query OR descripcion LIKE :query OR resource_type LIKE :query OR steam_area"
      @resources = @resources.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @recurso = Recurso.find(params[:id])
  end

  def new
    @recurso = Recurso.new
  end

  def create
    @recurso = Recurso.create(resource_params)
    if @recurso.save
      redirect_to @recurso, notice: "Resource created succssfully"
    else
      render :new
    end
  end

  def update
    if @recurso.update(resource_params)
      redirect_to @recurso, notice: "Resource updated succssfully"
    else
      render :edit
    end
  end

  def destroy
    @recurso.destroy
    redirect_to recursos_path, notice: "Resource deleted succssfully"
  end

  private

  def resource_params
    params.require(:recurso).permit(:titulo, :url, :descripcion, :steam_area, :category_id, :image, :resource_type)
  end

  def set_resource
    @recurso = Recurso.find(params[:id])
  end

  # def authenticate_admin!
  #   redirect_to root_path unless current_user.admin?
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recursos_helper.rb
module RecursosHelper
end

app/views/contacts/_contact_form.html.erb
<div class="contact-form">
  <%= form_with model: @contact, local: true, url: contacts_path, data: { turbo: false } do |form| %>
    <div>
      <%= form.label :name,  t('activerecord.attributes.contact.name'), class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div>
      <%= form.label :email,  t('activerecord.attributes.contact.email'), class: "form-label" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>

    <div>
      <%= form.label :message,  t('activerecord.attributes.contact.message'), class: "form-label" %>
      <%= form.text_area :message, class: "form-control textarea-control" %>
    </div>

    <div>
      <%= form.submit t('helpers.submit.contact'), class: "resources-button" %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<h1>Contáctanos</h1>

<%= render 'contact_form' %>

app/views/home/_about.html.erb
<div class="section-content">
  <div data-controller="scroll">
    <div data-scroll-target="section" class="section-container" id="about">
      <%= image_tag 'idea.png', alt: 'Steam', class: 'cuate-image' %>
      <section>
        <h2 class="section-title"><strong><%= t('lyralab.about_1.title') %></strong></h2>
        <p class="lyra-description"><%= t('lyralab.about_1.description') %></p>
      </section>
    </div>

    <div data-scroll-target="section" class="section-container" id="about">
      <%= image_tag 'computer.png', alt: 'Computer', class: 'cuate-image' %>
      <section>
        <h2 class="section-title"><strong><%= t('lyralab.about_2.title').html_safe %></strong></h2>
        <p class="lyra-description"><%= t('lyralab.about_2.description') %></p>
      </section>
    </div>

    <div data-scroll-target="section" class="section-container" id="about">
      <%= image_tag 'girls.png', alt: 'Woman', class: 'cuate-image' %>
      <section>
        <h2 class="section-title"><strong><%= t('lyralab.about_3.title') %></strong></h2>
        <p class="lyra-description"><%= t('lyralab.about_3.description') %></p>
      </section>
    </div>
  </div>
</div>

app/views/home/_banner.html.erb
<div class="banner-container">
  <%= image_tag 'lab.png', alt: 'lyralab', class: 'banner-img' %>
  <div class="banner-text">
    <h1 class="banner-title mt-3 align-content-center"><%= t('lyralab.banner_title').html_safe %>,</h1>
    <p class="slogan"><%= t('lyralab.banner_description') %></p>
    <button class="start-button mt-2" data-toggle="modal" data-target="#joinModal"><%= t('lyralab.buttons.join') %></button>
  </div>
</div>

app/views/home/_contact.html.erb
<div data-controller="scroll">
  <div data-scroll-target="section" class="section-container" id="contact">
    <section>
      <h2 class="section-title"><%= t('lyralab.contact.title') %></h2>
      <p class="section-text"><%= t('lyralab.contact.description') %></p>
      <%= render 'contacts/contact_form' %>
    </section>
    <%= image_tag 'contact.png', alt: 'lyralab', class: 'contact-img' %>
  </div>
<div>

app/views/home/_founders.html.erb
<div class="founders-container">
  <div class="founder">
    <%= image_tag 'valentina.jpeg', alt: 'Valentina', class: 'founder-image' %>
    <section class="founder-info">
      <div class="lyra-founder"><%= t('lyralab.co-founders.vale') %></div>
      <div class="description">
        <p><%= t('lyralab.co-founders.vale-description') %></p>
      </div>
    </section>
  </div>

  <div class="founder">
    <%= image_tag 'cinthya.jpeg', alt: 'Cinthya', class: 'founder-image' %>
    <section class="founder-info">
      <div class="lyra-founder"><%= t('lyralab.co-founders.cinthya') %></div>
      <div class="description">
        <p><%= t('lyralab.co-founders.cinthya-description') %></p>
      </div>
    </section>
  </div>
  <div id='planet'>
    <%= image_tag 'planet.png', alt: 'planet', class: 'planet-img' %>
  </div>
</div>

app/views/home/_modal.html.erb
<div class="modal fade" id="joinModal" tabindex="-1" role="dialog" aria-labelledby="joinModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="joinModalLabel">Únete a LyraLab</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="name">Nombre</label>
            <input type="text" class="form-control" id="name" placeholder="Tu nombre">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" placeholder="Tu email">
          </div>
          <div class="form-group">
            <label for="interest">Intereses</label>
            <textarea class="form-control" id="interest" rows="3" placeholder="¿Qué te interesa?"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary">Enviar</button>
      </div>
    </div>
  </div>
</div>

app/views/home/_proposition.html.erb
<div class="mt-5" data-controller="scroll">
  <div data-scroll-target="section" class="section-container" id="proposition">
    <section>
      <h2 class="recommendation-title"><%= t('lyralab.courses.title') %></h2>
    </section>
    <div class="position-card-container">
        <div class="position-card">
          <h3 class="position-card-title">Google Project Management Course</h3>
          <p class="position-card-description">Accede a recursos recomendados en tu área de interés.</p>
          <a href="https://www.coursera.org/professional-certificates/google-project-management?" class="btn-recommendation" target="_blank"><%= t('lyralab.buttons.see-more') %></a>
        </div>

        <div class="position-card">
          <h3 class="position-card-title">Introduction to Generative AI with Google Cloud</h3>
          <p class="position-card-description">introductory level microlearning course aimed at explaining what Generative AI is, how it is used, and how it differs from traditional machine learning methods.</p>
          <a href="https://www.udacity.com/course/introduction-generative-ai-google-cloud--cd12957" class="btn-recommendation" target="_blank"><%= t('lyralab.buttons.see-more') %></a>
        </div>

        <div class="position-card">
          <h3 class="position-card-title">Historia del Arte: Del Barroco al Arte Posmoderno</h3>
          <p class="position-card-description">Engage in a community of young learners to create</p>
          <a href="https://www.coursera.org/learn/historia-arte-barroco-posmoderno" class="btn-recommendation" target="_blank"><%= t('lyralab.buttons.see-more') %></a>
        </div>

        <div class="position-card">
          <h3 class="position-card-title">Matemáticas fundamentales para Ciencias de la Computación</h3>
          <p class="position-card-description">Definiciones y pruebas, Conjuntos y funciones, Relaciones, Estructuras discretas, Teoría de Grafos...</p>
          <a href="https://www.udemy.com/course/fundamental-concepts-of-mathematics-for-computer-science/?amp=&aff_code=Ewh3Y1lWQH8FQR93MkBPbG1RGXFfW1h8B14ZeU5TQ3YBRxFzWj5XMRM%3D&pmtag=CAREERS24LEARN15&utm_source=adwords&utm_medium=udemyads&utm_campaign=Search_DSA_GammaCatchall_NonP_la.EN_cc.ROW-English&campaigntype=Search&portfolio=ROW-English&language=EN&product=Course&test=&audience=DSA&topic=&priority=Gamma&utm_content=deal4584&utm_term=_._ag_169801645584_._ad_700876640599_._kw__._de_c_._dm__._pl__._ti_dsa-1456167871416_._li_9073882_._pd__._&matchtype=&gad_source=1&gclid=Cj0KCQjw05i4BhDiARIsAB_2wfBVGShlKzvmYuOE5qJYx11CY1ugAZ0_1j7vNGQ0QRK4dl3ie31_70IaAp7AEALw_wcB" class="btn-recommendation" target="_blank"><%= t('lyralab.buttons.see-more') %></a>
        </div>
    </div>
  </div>
<div>

app/views/home/_resources.html.erb
<div data-controller="scroll">
  <div data-scroll-target="section" class="section-container" id="resources">
    <section>
      <h2 class="section-title"><%= t('lyralab.resources.title') %></h2>
      <p class="lyra-description"><%= t('lyralab.resources.description') %></p>
      <%= link_to t('lyralab.buttons.see-resources'), recursos_path, class: 'resources-button' %>
    </section>
  </div>
<div>

app/views/home/_section.html.erb
<div class="sdg-title-img">
  <%= image_tag 'sdg.png', alt: 'SDG', id:"sdg-img" %>
</div>

<div class="sdg-container">
  <div class="sdgs">
    <%= image_tag 'education.jpg', alt: 'SDG 1', class: 'sdg' %>
    <%= image_tag 'equality.jpg', alt: 'SDG 2', class: 'sdg' %>
    <%= image_tag 'inequalities.jpg', alt: 'SDG 3', class: 'sdg' %>
    <%= image_tag 'climate.jpg', alt: 'SDG 2', class: 'sdg' %>
    <%= image_tag 'partnership.jpg', alt: 'SDG 4', class: 'sdg' %>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'banner' %>
<%= render 'about' %>
<%= render 'founders' %>
<%= render 'resources' %>
<%= render 'section' %>
<%= render 'proposition' %>
<%= render 'contact' %>
<%= render 'modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lyralab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/recursos/_recursos.html.erb
<div class="results-grid">
  <% resources.each do |recurso| %>
    <div class="resource-card">
      <div class="card-body">
        <h6><%= recurso.titulo %></h6>
        <p><%= recurso.steam_area %></p>
        <a href="<%= recurso.url %>" class="card-btn" target="_blank">Ver Más</a>
      </div>
    </div>
  <% end %>
  <% if resources.empty? %>
    <p>No se encontraron recursos</p>
  <% end %>
</div>

app/views/recursos/index.html.erb
<div class="resources-header">
  <div class="r-header">
    <h1 class="resources-title">The Lyra-Library</h1>
    <p class="resources-description"><%= t('resources-page.description') %></span></p>
    <div class="search-bar mt-2">
      <%= form_with url: recursos_path, method: :get, class: "d-flex align-items-center" do %>
        <%= text_field_tag :query, params[:query], class: "search-bar" %>
        <button type="submit" class="btn-search">
          <i class="fas fa-search"></i>
        </button>
      <% end %>
    </div>
  </div>
  <%= image_tag 'Innovation-bro.png', alt: 'library', class: 'resources-img' %>
</div>


<div class="resources-container">
  <% @steam_areas.each do |area| %>
    <div class="area-section <%= area.parameterize %>">
      <h2 class="area-title <%= area.parameterize %>"><%= area %></h2>
      <div class="cards-scroll-wrapper">
        <%= render 'recursos', resources: @resources.where(steam_area: area) %>
      </div>
    </div>
  <% end %>
</div>

app/views/recursos/new.html.erb
<div class="form-container mt-4">
  <%= image_tag 'equation.png', class: 'background-img equation' %>
  <%= image_tag 'sun.png', class: 'background-img sun' %>
  <%= image_tag 'purple.png', class: 'background-img purple' %>

  <div class="new-resource-card"
    <h1 id="new-resource-header">Nuevo Recurso</h1>
    <div class="new-resource-form">
      <%= simple_form_for @recurso, html: { multipart: true } do |f| %>
        <%= f.input :titulo, label: 'Titulo' %>
        <%= f.input :category_id,
                    label: "Categoría",
                    collection: Category.all.collect { |category| [category.name, category.id] },
                    prompt: "Selecciona una Categoría" %>
        <%= f.input :descripcion, label: "Descripción" %>
        <%= f.input :url, label: "URL del recurso" %>
        <%= f.input :image, as: :file, label: "Imágen de Referencia" %>
        <%= f.input :steam_area, label: "Área STEAM" %>
        <%= f.input :resource_type, label: "Tipo de recurso" %>
        <%= f.button :submit %>
      <%end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-container">
    <div class="social-icons">
      <a href="https://www.instagram.com/lyra.labs?igsh=MWo2bDAzZmV5c2h3dw=="><i class="fab fa-instagram"></i></a>
    </div>
    <div>
      <p class='text-dark'>&copy; 2024 LyraLab</p>
    </div>
  </div>
</footer>

app/views/shared/_language_menu.html.erb
<%= form_tag '', method: :get, class: 'language-form' do %>
  <%= select_tag :locale, options_for_select([['🇺🇸', 'en'], ['🇲🇽', 'es']], I18n.locale), onchange: 'this.form.submit();', class: 'language-select' %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <%= image_tag 'lyralablogo.png', alt: 'Logo', width: 150 %>
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Recursos', recursos_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#founders">Fundadoras</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#contact">Contacto</a>
      </li>
      <li class="nav-item">
        <%= render 'shared/language_menu' %>
      </li>
    </ul>
  </div>
</nav>